### ISSUE TITLE
VideoIter:: >> frame [] is error & backup is inavailable

### ISSUE THREAD

**Issue by Jiangchitang** [cypw/PyTorch-MFNet#20]
VideoIter:: >> frame [] is error & backup is inavailable. [./dataset/UCF101/raw/data/CricketBowling/v_CricketBowling_g22_c07.avi]'
2019-03-09 22:30:13: >> I/O error(None): None
2019-03-09 22:30:13: VideoIter:: ERROR!! (Force using another index:
3279)
VideoIter:: >> frame [] is error & backup is inavailable. [./dataset/UCF101/raw/data/TableTennisShot/v_TableTennisShot_g11_c05.avi]'
2019-03-09 22:30:13: VideoIter:: ERROR!! (Force using another index:
2801)
VideoIter:: >> frame [] is error & backup is inavailable. [./dataset/UCF101/raw/data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c05.avi]'

why I have this question?

**Comment by yunyunyunYYY** [comment]
Me too, It sounds like the video broken? Or it just nothing when the data used at all? But I was full screen this problem. My Env is python3.6,opencv3.1.0,cuda9.0,cudnn7.1.3,pytorch0.4.0,torchvision0.2.0,anaconda3-5.2.0,nvidia-smi 396.37. And I fix code with question#5(1 and 2).

**Comment by yunyunyunYYY** [comment]
@Jiangchitang I got it. This problem might be OpenCV's , when I reinstall Opencv by pip opencv-python and opencv-contrib-python (I used conda install opencv...   to install opencv first )and I run train_ucf101 again it has no problem.

**Comment by cypw** [comment]
This might be caused by OpenCV as noted by @ yunyunyunYYY.
