### ISSUE TITLE
2D Model

### ISSUE THREAD

**Issue by Esaada** [cypw/PyTorch-MFNet#23]
Hi, where can I find the 2D model? I don't mean the weights, I mean the code.
I see only mfnet3d.py  file...

Thanks.

**Comment by XuhongLuo** [comment]
yeah , i want to get the 2D model code too ,Thanks !

**Comment by cypw** [comment]
2D MF-Net is implemented by MXNet, where the code is inside the released `.tar` files: [GoogleDrive](https://goo.gl/53Gfsg)

Or, you can simply delete the 1st dimension of all 3D convolution layers in `mfnet3d.py` to get the PyTorch implementation of 2D MF-Net.
