### ISSUE TITLE
about can not download the knetics pretrained models

### ISSUE THREAD

**Issue by poweryin** [cypw/PyTorch-MFNet#27]
Hi,I can not download the knetics pretrained models at https://goo.gl/QdE85T

**Comment by cypw** [comment]
The link will redirect you to Google Drive, which requires a VPN if you are in China.

**Comment by zugexiaodui** [comment]
链接: https://pan.baidu.com/s/1gfu3lujt2lTHMDrZARUIZA 提取码: di5n 
I downloaded the pretrained models. You can download them from the above link if you use 'Baidu Netdisk'.

**Comment by poweryin** [comment]
Thanks very much

**Comment by poweryin** [comment]
Thanks very much
