### ISSUE TITLE
Initial weights

### ISSUE THREAD

**Issue by yoniaflalo** [cypw/PyTorch-MFNet#3]
Hi.

I see that the code requires initialisation weights from kinetics (vY5_866M_Kinetics_v50_fm16-it123_ep-0019.pth).

Where can we find it?

Thanks

**Comment by cypw** [comment]
Please use the model pretrained on Kinetics, i.e. https://goo.gl/QdE85T.

I forgot to change the name. : )

**Comment by yoniaflalo** [comment]
Thanks a lot :-)

**Comment by poweryin** [comment]
hi,I can not open https://goo.gl/QdE85T  ,can you help me?thanks
