### ISSUE TITLE
testing on kinetics takes long time? 

### ISSUE THREAD

**Issue by gooners1886** [cypw/PyTorch-MFNet#7]
This is some main configs:

    "batch_size": 8,
    "clip_length": 16,
    "dataset": "Kinetics",
    "debug_mode": true,
    "frame_interval": 2,
    "model_prefix": "././../exps/models/MFNet3D_Kinetics-400_72.8.pth",
    "network": "mfnet_3d",
    "task_name": "./../exps/models/MFNet3D_Kinetics-400_72.8.pth"

I use 4 Telsa-P40 and 48 cpu cores to test the model on Kinetics val set (19761 videos) with 10 round. 
It takes about 27hours (10 round)
Is this a normal speed? 
Is there some trick to speed up the dataloader?

**Comment by cypw** [comment]
Convert the *.mp4 to *.avi can significantlty speed up the decoding stage:
For example:
ffmpeg -y -i ${SRC_VID} -c:v mpeg4 -filter:v "scale=min(iw\,(256*iw)/min(iw\,ih)):-1" -b:v 512k -an ${DST_VID}

**Comment by gooners1886** [comment]
Thank you.

**Comment by buaa-luzhi** [comment]
@cypw @gooners1886 
Hello. 
Out of memory will occur during the training and testing of ucf-101 data.  I only have a 32G CPU. Is this a normal phenomenon? How much memory is needed to train the network properly? 
Thank you very much!
